<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>1</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>247</x>
			<y>511</y>
		</node>
		<node>
			<index>3</index>
			<img>image/port_100m_lc_right_gray.gif</img>
			<direction>1</direction>
			<x>10</x>
			<y>606</y>
		</node>
		<node>
			<index>4</index>
			<img>image/port_100m_lc_right_gray.gif</img>
			<direction>1</direction>
			<x>11</x>
			<y>579</y>
		</node>
		<node>
			<index>5</index>
			<img>image/port_100m_lc_right_gray.gif</img>
			<direction>1</direction>
			<x>11</x>
			<y>553</y>
		</node>
		<node>
			<index>6</index>
			<img>image/port_100m_lc_right_gray.gif</img>
			<direction>1</direction>
			<x>11</x>
			<y>528</y>
		</node>
		<node>
			<index>7</index>
			<img>image/port_100m_lc_right_gray.gif</img>
			<direction>1</direction>
			<x>11</x>
			<y>502</y>
		</node>
		<node>
			<index>8</index>
			<img>image/port_100m_lc_right_gray.gif</img>
			<direction>1</direction>
			<x>11</x>
			<y>477</y>
		</node>
		<node>
			<index>9</index>
			<img>image/port_100m_lc_right_gray.gif</img>
			<direction>1</direction>
			<x>11</x>
			<y>452</y>
		</node>
		<node>
			<index>10</index>
			<img>image/port_100m_lc_right_gray.gif</img>
			<direction>1</direction>
			<x>11</x>
			<y>427</y>
		</node>
		<node>
			<index>13</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>508</x>
			<y>412</y>
		</node>
		<node>
			<index>14</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>507</x>
			<y>382</y>
		</node>
		<node>
			<index>15</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>681</y>
		</node>
		<node>
			<index>16</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>659</y>
		</node>
		<node>
			<index>17</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>640</y>
		</node>
		<node>
			<index>18</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>528</x>
			<y>619</y>
		</node>
		<node>
			<index>19</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>547</x>
			<y>681</y>
		</node>
		<node>
			<index>20</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>548</x>
			<y>661</y>
		</node>
		<node>
			<index>21</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>548</x>
			<y>640</y>
		</node>
		<node>
			<index>22</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>548</x>
			<y>619</y>
		</node>
		<node>
			<index>23</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>595</y>
		</node>
		<node>
			<index>24</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>573</y>
		</node>
		<node>
			<index>25</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>527</x>
			<y>554</y>
		</node>
		<node>
			<index>26</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>534</y>
		</node>
		<node>
			<index>27</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>548</x>
			<y>595</y>
		</node>
		<node>
			<index>28</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>547</x>
			<y>575</y>
		</node>
		<node>
			<index>29</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>546</x>
			<y>554</y>
		</node>
		<node>
			<index>30</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>546</x>
			<y>533</y>
		</node>
		<node>
			<index>31</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>525</x>
			<y>510</y>
		</node>
		<node>
			<index>32</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>488</y>
		</node>
		<node>
			<index>33</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>464</y>
		</node>
		<node>
			<index>34</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>526</x>
			<y>442</y>
		</node>
		<node>
			<index>35</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>546</x>
			<y>510</y>
		</node>
		<node>
			<index>36</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>547</x>
			<y>487</y>
		</node>
		<node>
			<index>37</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>547</x>
			<y>465</y>
		</node>
		<node>
			<index>38</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>547</x>
			<y>442</y>
		</node>
		<node>
			<index>39</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>528</x>
			<y>420</y>
		</node>
		<node>
			<index>40</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>529</x>
			<y>397</y>
		</node>
		<node>
			<index>41</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>530</x>
			<y>374</y>
		</node>
		<node>
			<index>42</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>530</x>
			<y>351</y>
		</node>
		<node>
			<index>43</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>547</x>
			<y>419</y>
		</node>
		<node>
			<index>44</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>548</x>
			<y>397</y>
		</node>
		<node>
			<index>45</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>549</x>
			<y>374</y>
		</node>
		<node>
			<index>46</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>551</x>
			<y>351</y>
		</node>
		<node>
			<index>49</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>406</x>
			<y>659</y>
		</node>
		<node>
			<index>50</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>405</x>
			<y>633</y>
		</node>
		<node>
			<index>51</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>404</x>
			<y>607</y>
		</node>
		<node>
			<index>52</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>403</x>
			<y>582</y>
		</node>
		<node>
			<index>53</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>404</x>
			<y>539</y>
		</node>
		<node>
			<index>54</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>405</x>
			<y>513</y>
		</node>
		<node>
			<index>55</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>405</x>
			<y>488</y>
		</node>
		<node>
			<index>56</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>405</x>
			<y>463</y>
		</node>
		<node>
			<index>57</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>427</x>
			<y>659</y>
		</node>
		<node>
			<index>58</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>426</x>
			<y>632</y>
		</node>
		<node>
			<index>59</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>424</x>
			<y>608</y>
		</node>
		<node>
			<index>60</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>426</x>
			<y>583</y>
		</node>
		<node>
			<index>61</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>427</x>
			<y>539</y>
		</node>
		<node>
			<index>62</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>427</x>
			<y>513</y>
		</node>
		<node>
			<index>63</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>426</x>
			<y>489</y>
		</node>
		<node>
			<index>64</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>426</x>
			<y>464</y>
		</node>
		<node>
			<index>67</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>127</x>
			<y>659</y>
		</node>
		<node>
			<index>68</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>126</x>
			<y>635</y>
		</node>
		<node>
			<index>69</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>125</x>
			<y>610</y>
		</node>
		<node>
			<index>70</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>125</x>
			<y>584</y>
		</node>
		<node>
			<index>71</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>125</x>
			<y>521</y>
		</node>
		<node>
			<index>72</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>124</x>
			<y>495</y>
		</node>
		<node>
			<index>73</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>124</x>
			<y>468</y>
		</node>
		<node>
			<index>74</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>125</x>
			<y>442</y>
		</node>
		<node>
			<index>75</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>151</x>
			<y>644</y>
		</node>
		<node>
			<index>76</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>151</x>
			<y>606</y>
		</node>
	</nodes>
</root>

