<%@page contentType="text/html; charset=GB2312"%>
<?xml version="1.0" encoding="GB2312"?>
<root>
	<nodes>
		<node>
			<index>3</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>40</x>
			<y>126</y>
		</node>
		<node>
			<index>4</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>16</x>
			<y>126</y>
		</node>
		<node>
			<index>5</index>
			<img>image/port_10000m_left_gray.gif</img>
			<direction>1</direction>
			<x>34</x>
			<y>298</y>
		</node>
		<node>
			<index>6</index>
			<img>image/port_10000m_left_gray.gif</img>
			<direction>1</direction>
			<x>169</x>
			<y>300</y>
		</node>
		<node>
			<index>7</index>
			<img>image/port_10000m_left_gray.gif</img>
			<direction>1</direction>
			<x>27</x>
			<y>554</y>
		</node>
		<node>
			<index>8</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>574</x>
			<y>125</y>
		</node>
		<node>
			<index>9</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>550</x>
			<y>125</y>
		</node>
		<node>
			<index>10</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>574</x>
			<y>603</y>
		</node>
		<node>
			<index>11</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>575</x>
			<y>581</y>
		</node>
		<node>
			<index>12</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>576</x>
			<y>559</y>
		</node>
		<node>
			<index>13</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>576</x>
			<y>536</y>
		</node>
		<node>
			<index>14</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>578</x>
			<y>514</y>
		</node>
		<node>
			<index>15</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>578</x>
			<y>492</y>
		</node>
		<node>
			<index>16</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>578</x>
			<y>469</y>
		</node>
		<node>
			<index>17</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>577</x>
			<y>447</y>
		</node>
		<node>
			<index>18</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>544</x>
			<y>601</y>
		</node>
		<node>
			<index>19</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>545</x>
			<y>580</y>
		</node>
		<node>
			<index>20</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>545</x>
			<y>557</y>
		</node>
		<node>
			<index>21</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>545</x>
			<y>534</y>
		</node>
		<node>
			<index>22</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>545</x>
			<y>512</y>
		</node>
		<node>
			<index>23</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>546</x>
			<y>490</y>
		</node>
		<node>
			<index>24</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>546</x>
			<y>468</y>
		</node>
		<node>
			<index>25</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>546</x>
			<y>446</y>
		</node>
		<node>
			<index>26</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>175</x>
			<y>124</y>
		</node>
		<node>
			<index>27</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>150</x>
			<y>125</y>
		</node>
		<node>
			<index>28</index>
			<img>image/port_10000m_left_gray.gif</img>
			<direction>1</direction>
			<x>36</x>
			<y>207</y>
		</node>
		<node>
			<index>29</index>
			<img>image/port_10000m_left_gray.gif</img>
			<direction>1</direction>
			<x>169</x>
			<y>210</y>
		</node>
		<node>
			<index>30</index>
			<img>image/port_10000m_left_gray.gif</img>
			<direction>1</direction>
			<x>159</x>
			<y>556</y>
		</node>
		<node>
			<index>31</index>
			<img>image/port_ethernet_right_gray.gif</img>
			<direction>1</direction>
			<x>440</x>
			<y>127</y>
		</node>
		<node>
			<index>32</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>415</x>
			<y>126</y>
		</node>
		<node>
			<index>33</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>440</x>
			<y>605</y>
		</node>
		<node>
			<index>34</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>440</x>
			<y>583</y>
		</node>
		<node>
			<index>35</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>440</x>
			<y>561</y>
		</node>
		<node>
			<index>36</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>441</x>
			<y>538</y>
		</node>
		<node>
			<index>37</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>442</x>
			<y>515</y>
		</node>
		<node>
			<index>38</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>442</x>
			<y>493</y>
		</node>
		<node>
			<index>39</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>442</x>
			<y>470</y>
		</node>
		<node>
			<index>40</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>441</x>
			<y>450</y>
		</node>
		<node>
			<index>41</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>409</x>
			<y>603</y>
		</node>
		<node>
			<index>42</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>409</x>
			<y>584</y>
		</node>
		<node>
			<index>43</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>408</x>
			<y>562</y>
		</node>
		<node>
			<index>44</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>408</x>
			<y>541</y>
		</node>
		<node>
			<index>45</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>409</x>
			<y>517</y>
		</node>
		<node>
			<index>46</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>409</x>
			<y>494</y>
		</node>
		<node>
			<index>47</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>410</x>
			<y>472</y>
		</node>
		<node>
			<index>48</index>
			<img>image/port_ethernet_left_gray.gif</img>
			<direction>1</direction>
			<x>409</x>
			<y>451</y>
		</node>
	</nodes>
</root>

